### ISSUE TITLE
node monitor command error

### ISSUE THREAD

**Issue by mrclouds1** [dzt/shopify-monitor#103]
Hi,

I think I've done the install correctly but everytime I run the node monitor command I get an error.

![help](https://user-images.githubusercontent.com/34816535/34328238-f4543dd2-e88e-11e7-81ce-e7dede7538be.png)

I've reinstalling but that didn't work. 

Any help is apperciated!

Thanks,

**Comment by cameronb23** [comment]
Instructions on what commands are used to run the monitor are located in the (readme)[https://github.com/dzt/shopify-monitor#installation] right below the image.

**Comment by LMascher** [comment]
Cameronb23 this doesn't help at all. I have same error and readme doesnt help one bit. Could you elaborate?
