### ISSUE TITLE
Unexpected token ] in JSON at position 1178

### ISSUE THREAD

**Issue by chad703** [dzt/shopify-monitor#112]
Just set this up following the tutorial in Youtube on a Windows 10 machine.

I get these errors when I start the monitor:

PM2        | App [shopify-monitor] with id [0] and pid [10608], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:shopify-monitor id:0
PM2        | App name:shopify-monitor id:0 online
0|shopify- | [Fri Jan 26 2018 08:41:18] [ERROR]
0|shopify- | SyntaxError: C:\Users\chad\Documents\git stuff\shopify-monitor\config.json: Unexpected token ] in JSON at position 1178
0|shopify- |     at JSON.parse (<anonymous>)
0|shopify- |     at Object.Module._extensions..json (module.js:662:27)
0|shopify- |     at Module.load (module.js:556:32)
0|shopify- |     at tryModuleLoad (module.js:499:12)
0|shopify- |     at Function.Module._load (module.js:491:3)
0|shopify- |     at Module.require (module.js:587:17)
0|shopify- |     at require (internal/module.js:11:18)
0|shopify- |     at Object.<anonymous> (C:/Users/chad/Documents/git stuff/shopify-monitor/index.js:12:16)
0|shopify- |     at Module._compile (module.js:643:30)
0|shopify- |     at loader (C:\Users\chad\Documents\git stuff\shopify-monitor\node_modules\babel-register\lib\node.js:144:5)
0|shopify- |     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\chad\Documents\git stuff\shopify-monitor\node_modules\babel-register\lib\node.js:154:7)
0|shopify- |     at Module.load (module.js:556:32)
0|shopify- |     at tryModuleLoad (module.js:499:12)
0|shopify- |     at Function.Module._load (module.js:491:3)
0|shopify- |     at Module.require (module.js:587:17)
0|shopify- |     at require (internal/module.js:11:18)
0|shopify- |     at Object.<anonymous> (C:\Users\chad\Documents\git stuff\shopify-monitor\app.js:2:1)
0|shopify- |     at Module._compile (module.js:643:30)
0|shopify- |     at Object.Module._extensions..js (module.js:654:10)
0|shopify- |     at Module.load (module.js:556:32)
0|shopify- |     at tryModuleLoad (module.js:499:12)
0|shopify- |     at Function.Module._load (module.js:491:3)

What am I doing wrong? Thanks for the help.

**Comment by cameronb23** [comment]
invalid configuration - json is incorrectly formatted
