### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Jeisonx3** [dzt/shopify-monitor#114]
<img width="886" alt="screen shot 2018-02-26 at 2 34 35 pm" src="https://user-images.githubusercontent.com/22186712/36691135-4fbebf58-1b02-11e8-93a4-dea2b0ca4499.png">

**Comment by gpicon6** [comment]
same, no clue 
<img width="1280" alt="untitled" src="https://user-images.githubusercontent.com/36881744/37442499-ef19e32a-27c3-11e8-8913-1c743985ac68.png">

**Comment by Jeisonx** [comment]
closing
