### ISSUE TITLE
Monitor freezing up after too many sites are added.

### ISSUE THREAD

**Issue by cjlatch125** [dzt/shopify-monitor#13]
Hey, I added a few sites and the monitor seems to be freezing up now after the searching for keywords message.

**Comment by dzt** [comment]
What's your monitor interval, how many sites do you have, and are you tweeting out info?

**Comment by cjlatch125** [comment]
1000, about 15 and it seems that i only get the monitor notifications every minute or two and it keeps says it is finding new products that have been on the sitemap.

**Comment by zhibolau** [comment]
make it 60,000.
