### ISSUE TITLE
Every Shopify website doesn't work

### ISSUE THREAD

**Issue by MisterCruz** [dzt/shopify-monitor#143]
I've bene using this monitor for a while without a problem. However now all the Shopify websites don't work. It says they're invalid

**Comment by aodsupport** [comment]
Welcome to the club. :) Ours did the same thing.  It worked for months and then did the same thing.  We disabled it and then I was going to try to have a developer see if they could resolve it, however, it miraculously started working again before anything was changed.  It worked for 2-3 weeks, but then started doing the same thing again.  Initial reports were that something on the Shopify API/Feed/XML side changed, but now it seems almost like some type of defense mechanism against the monitor.  I really don't know though.  Let us know when you get it fixed :)))

**Comment by riccardoravelli** [comment]
I'm having the same problems...

**Comment by MisterCruz** [comment]
Any updates?
