### ISSUE TITLE
sitemap comming up as empty 

### ISSUE THREAD

**Issue by jbij0219** [dzt/shopify-monitor#15]
occasionally the program will see the sitemap as empty and then see the sitemap with all products marking them all as new and attempting to tweet every item on the sitemap

**Comment by dzt** [comment]
@jbij0219 this means that your interval may be too low try setting it to 60000

**Comment by jbij0219** [comment]
@dzt set interval to 80000 and still same problem. i think that if there are over 100 new items "added" (not really added) it should just pass that read through of the sitemap as it probably picked it up as empty on one read through and then filled on the next.

**Comment by zhibolau** [comment]
just wondering if interval is like 60,000, the monitor will pick up item not immediately? like 60s later max? thanks
