### ISSUE TITLE
incorrect match found

### ISSUE THREAD

**Issue by toomuchsoul** [dzt/shopify-monitor#16]
When the monitor first starts up the correct matches are found but when it continues running random items are matched that do not contain any of the key words.

**Comment by ronmo32992** [comment]
same happen to me

**Comment by toomuchsoul** [comment]
ok so trying different test cases I noticed some thing:
If my computer goes to sleep while the monitor is running once it wakes up it will send out notifications for over 80+ products that have nothing to do with my key words.
Might be a memory managing issue.

**Comment by dzt** [comment]
@toomuchsoul @ronmo32992 From what I've seen this is a thing brands are doing at times the hide all items and read them for maintenance purposes. The monitor does not just pick up keywords it picks up sell outs, restocks, and new items.

**Comment by toomuchsoul** [comment]
ah ok I see thank you. Also in the readme.md there is an image of the monitor sending size link for the products how do we achieve this? thank you

![68747470733a2f2f692e696d6775722e636f6d2f3836476e4b48442e6a7067](https://cloud.githubusercontent.com/assets/25241131/22185462/dc5499c2-e09a-11e6-94a2-76b77ef0f461.jpeg)

**Comment by nolove22** [comment]
@toomuchsoul you need Slackm He stated in his tut video he will make a new video on how to connect the monitor to slack.

**Comment by dzt** [comment]
@toomuchsoul @nolove22 Once you get the bot token and add it to a channel like #monitor you can change the channel in the config file you have to run `/invite <slack bot name>` into the channel sorry for the misunderstanding I'll add it to the wiki.

**Comment by nolove22** [comment]
Got it, Thanks! Now what will be the best way to integrate ur ATC with the monitor

**Comment by nolove22** [comment]
i got it to work, but getting this error

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'urlset' of null

**Comment by nolove22** [comment]
the slackbot works great however i ran into this error a few hours later and cant seem to fix it. 

![error](https://cloud.githubusercontent.com/assets/20826323/22232617/83888f96-e1b8-11e6-89e8-6bc4cf23c033.PNG)

**Comment by toomuchsoul** [comment]
@nolove22 I ran into this issue as well. My cause was a site i was checking was down so the xml couldn't be parsed. I'd try just a few sites and see if that fixes your error. Btw did you get the atc links to work?

**Comment by nolove22** [comment]
same, it tampered with sites and managed to work. Wasn't sure which site though. do you mean the atc he posted as a Repo or atc in slack?

**Comment by toomuchsoul** [comment]
@nolove22 ok nice dude, the add to cart 🚪 size links  in  slack

**Comment by toomuchsoul** [comment]
@nolove nvm I fixed it
