### ISSUE TITLE
Twitter Issue 

### ISSUE THREAD

**Issue by add267** [dzt/shopify-monitor#17]
So Slack seems to be working fine. However, twitter doesn't seem to tweet everything as slack does. What could it be?

**Comment by dzt** [comment]
Twitter only tweets new items and restocks. This is intentional to prevent spam.

--
Peter Soboyejo / GitHub l Website l LinkedIn

**Comment by add267** [comment]
Oh ok. I was wondering cause for the twitter. It would tweet items that are not even the keywords listed in my config file. Is there anyway to trouble shoot that?

**Comment by zhibolau** [comment]
maybe it make "new" true in config.
