### ISSUE TITLE
setup slack

### ISSUE THREAD

**Issue by jay55** [dzt/shopify-monitor#18]
I have the bot and slash command integration setup but how do i get the notifications?

**Comment by dzt** [comment]
How do you get Notifications on what and here is a good example.

**Comment by jay55** [comment]
Sorry, what I meant was how do I go about utilizing Slack? After creating the bot and slash integrations: I've added the token and username to the .json. Should that be all i need Or on the slack side do I need to have both the bot and slash setup together in a public channel?

**Comment by HamzaM** [comment]
Once you created the bot and modified the filled the config file with your token, you just need to add the bot to one of slack team channels and that's it.

**Comment by jay55** [comment]
Sorry, I figured it out shortly after i posted the last update this morning. Had an extra letter in the channel name.
