### ISSUE TITLE
Slack Display

### ISSUE THREAD

**Issue by jbt310** [dzt/shopify-monitor#26]
I've updated the API token for the slack integration in the json file and the channel shows when the shopify monitor is active, but it doesn't show the updated items (they show up in the terminal window though). How do I integrate that?

**Comment by dzt** [comment]
Check the notify section under your `config.json` file

**Comment by jbt310** [comment]
I set both new and keywords to true. The results only popped up in the terminal, but not the slack channel.

**Comment by zhibolau** [comment]
you have to use slack token, create your Chanel and bot configuration.

**Comment by cameronb23** [comment]
Make sure your Slack configuration is correct 💯
