### ISSUE TITLE
npm WARN shopify-monitor@1.0.0 No repository field.

### ISSUE THREAD

**Issue by GAWDTHREADS** [dzt/shopify-monitor#31]
![image](https://cloud.githubusercontent.com/assets/25658561/22775662/8ddba702-ee61-11e6-8f94-c91b3ce18acd.png)

![image](https://cloud.githubusercontent.com/assets/25658561/22775675/9c59f00e-ee61-11e6-881c-521f8d002372.png)

**Comment by vercepablo** [comment]
Same issue

**Comment by magboo** [comment]
i think you need to install nodejs first

**Comment by dzt** [comment]
This issue has been resolved please update your version of shopify-monitor.
