### ISSUE TITLE
Setting up on linux server

### ISSUE THREAD

**Issue by rizzryan** [dzt/shopify-monitor#38]
When I click on the setting up on linux server, it takes me to the Slack configuration guide you made

**Comment by arjunblj** [comment]
There isn't actually a page up on the wiki for this now so it's probably just a placeholder. What are you having trouble with re: setup? 

Check out this [page](http://blog.teamtreehouse.com/install-node-js-npm-linux) which has instructions on getting bode `node` and `npm` set up on a fresh Linux machine (regardless of distribution). Once you get this, you should be able to `npm install` this project's dependencies to run it.

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase. We will hopefully be able to release guides for these things once V2 is stable and tested on all platforms.
