### ISSUE TITLE
Atc 

### ISSUE THREAD

**Issue by doggy30** [dzt/shopify-monitor#42]
hi ATC don't work ? need to open with program
![salck](https://cloud.githubusercontent.com/assets/26242792/23808778/63db0872-05cb-11e7-9086-9b4887d35c3a.JPG)

**Comment by OneLifeOnly** [comment]
you click on Default Title since it doesn't have a size, did you even try clicking on that?

**Comment by doggy30** [comment]
ok, i know my mistake, i need to click on the size, not on ATC
