### ISSUE TITLE
Not an issue, more of a suggestion.

### ISSUE THREAD

**Issue by Jeisonx3** [dzt/shopify-monitor#44]
<img width="316" alt="screen shot 2017-03-15 at 11 23 19 am" src="https://cloud.githubusercontent.com/assets/22186712/23971069/c09fa6aa-09a2-11e7-8fcb-ca6b7715c9f6.png">
Can something like this or similar be added when using slack?  Most of the time i end up with the same item (product) sent to the slacked group like 11 times.

**Comment by YeezySzn** [comment]
Yo can you help me I cant get it to run on my mac

**Comment by Jeisonx3** [comment]
@YeezySzn did you get it to work? @dzt got another suggestion can you make that if total stock = 0 not tweet or send it to slack?

**Comment by cameronb23** [comment]
Version 2 has been released and I believe the issue referenced by OP has been eliminated. We are now using SQLite to cache product status.
