### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Jeisonx3** [dzt/shopify-monitor#47]
lately i've getting this error after like 1 or 2 hours of the monitor running.
<img width="930" alt="screen shot 2017-03-24 at 4 23 31 pm" src="https://cloud.githubusercontent.com/assets/22186712/24323079/aa5faa74-1146-11e7-8542-0bc76a94510a.png">

**Comment by washedogg** [comment]
try running as admin.

**Comment by Jeisonx3** [comment]
@washedogg I'm on a mac.

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase - please attempt on version 2 and reopen if your issue still arises, or create a new one if a different bug appears.
