### ISSUE TITLE
Struggle

### ISSUE THREAD

**Issue by ethanperson** [dzt/shopify-monitor#5]
I get this error when I enter $ npm install
Missing, config.json file or invalid json syntax.

I ran the config.json file through jsonlint and it says it was valid

**Comment by ac-daman** [comment]
I'm having the same problem

**Comment by dzt** [comment]
1. Did you rename the file to `config.json`?
2. Is the JSON actually valid? Take the text and run it through a linter like [this](jsonlint.com) one.

**Comment by CarrotShock** [comment]
Error: Parse error on line 1:
"interval": 1000,"serverPort"
----------^
Expecting 'EOF', '}', ',', ']', got ':'

Is what I'm getting. (have same issue)

**Comment by dzt** [comment]
@CarrotShock Can you [email](mailto:thepcmrtim@gmail.com) me your config so I can fix it for you.

**Comment by CarrotShock** [comment]
Just did @dzt

**Comment by dzt** [comment]
@CarrotShock Just emailed you the fix to the file.

**Comment by CarrotShock** [comment]
Thanks!
