### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by akronwonderkid** [dzt/shopify-monitor#50]
![monitor](https://cloud.githubusercontent.com/assets/25414485/24583925/d4c848f6-170f-11e7-94d5-017e6977aa8e.jpg)

How do you fix this error?

**Comment by jrodwhit** [comment]
Still haven't solved this.  Increase interval for temporary fix.

**Comment by cameronb23** [comment]
Version 2 has been released recently with many improvements and an overall better codebase - try again with this and let us know of any new issues.
