### ISSUE TITLE
Stock Count: 

### ISSUE THREAD

**Issue by echodotdot** [dzt/shopify-monitor#52]
Can someone teach me how to remove this Stock Count in monitor.js Thanks
WMNS Adidas NMD_R1 - Black/White/Grey
$140.00
Stock Count: Unavailable

but when i clicked there are sizes available. 
i just want to remove that Stock Count. Thanks

**Comment by dzt** [comment]
Not all sites provide a stock count. "Unavailable" doesn't mean there is no stock it means there isn't a set value due to the lack of an exposed count.

--
Peter Soboyejo / GitHub l Website l LinkedIn

**Comment by echodotdot** [comment]
but can i remove the stock count thing in monitor.js? i saw other monitor tweets with no stock counts. Thanks

**Comment by OddOsprey** [comment]
Echo, you aren't asking an issue. Don't burden the dev by asking how to code. You can remove the stock count in monitor.js. Just go through the code and ensure it doesn't throw any errors.
