### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Jeisonx3** [dzt/shopify-monitor#54]
keep getting this errors after 2 - 10 minutes.
<img width="954" alt="screen shot 2017-04-07 at 1 45 44 am" src="https://cloud.githubusercontent.com/assets/22186712/24787062/0705958a-1b34-11e7-898c-9c1778027311.png">

<img width="926" alt="screen shot 2017-04-07 at 12 58 32 am" src="https://cloud.githubusercontent.com/assets/22186712/24787072/10013590-1b34-11e7-94b0-c80158fdc3e1.png">

**Comment by OddOsprey** [comment]
Similar issue
events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
    at /root/shopify-monitor/monitor.js:338:62
    at Array.forEach (native)
    at api.getItems (/root/shopify-monitor/monitor.js:292:14)
    at /root/shopify-monitor/api.js:91:20
    at /root/shopify-monitor/node_modules/async/dist/async.js:3824:9
    at /root/shopify-monitor/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/root/shopify-monitor/node_modules/async/dist/async.js:1034:13)
    at /root/shopify-monitor/node_modules/async/dist/async.js:944:16
    at /root/shopify-monitor/node_modules/async/dist/async.js:3821:13
    at apply (/root/shopify-monitor/node_modules/async/dist/async.js:21:25)
