### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Yahg** [dzt/shopify-monitor#57]
<--- Last few GCs --->

 2626701 ms: Mark-sweep 1344.6 (1435.1) -> 1344.6 (1435.1) MB, 1975.0 / 1.0 ms [
allocation failure] [GC in old space requested].
 2628694 ms: Mark-sweep 1344.6 (1435.1) -> 1344.6 (1435.1) MB, 1992.0 / 2.0 ms [
allocation failure] [GC in old space requested].
 2630756 ms: Mark-sweep 1344.6 (1435.1) -> 1348.1 (1419.1) MB, 2062.0 / 3.0 ms [
last resort gc].
 2632845 ms: Mark-sweep 1348.1 (1419.1) -> 1351.6 (1419.1) MB, 2089.0 / 3.0 ms [
last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000364F54CFB49 <JS Object>
    1: init [C:\Users\User\shopify-monitor\node_modules\request\request.js:455]
 [pc=0000021C0712952A] (this=0000027F183B0971 <a Request with map 000003ECEFDD06
09>,options=0000002294C1CC79 <an Object with map 00000310EDCA82E1>)
    2: new constructor(aka Request) [C:\Users\User\shopify-monitor\node_modules
\request\request.js:130] [pc=0000021C07130C47] (this=0000027F183B0971 <a Request
 with m...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memo
ry

I've been getting this error after about ~10 minutes of monitoring

**Comment by cameronb23** [comment]
How many sites are you monitoring? This could be an issue depending on the amount of resources you're using and the interval.

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase - please attempt on version 2 and reopen if your issue still arises, or create a new one if a different bug appears.
