### ISSUE TITLE
linux error with update

### ISSUE THREAD

**Issue by doggy30** [dzt/shopify-monitor#58]
New error

![shopify](https://cloud.githubusercontent.com/assets/26242792/24907086/ee72a24e-1eba-11e7-8f42-e0a3fdd965e1.png)

**Comment by doggy30** [comment]
Even with update

![shopify1](https://cloud.githubusercontent.com/assets/26242792/24907306/e6316e20-1ebb-11e7-8d4b-fa5312f1962d.png)

**Comment by doggy30** [comment]
found the answer , to many sites

**Comment by Kickbasic** [comment]
How'd u setup a linux serever
