### ISSUE TITLE
Shopify Monitor Stop/Start

### ISSUE THREAD

**Issue by cjlatch125** [dzt/shopify-monitor#6]
Hi, is there anyway to stop/start the monitor without it grabbing all the stock and posting notifications for that.

**Comment by dzt** [comment]
Are you talking about disabling the monitor from finding keyword matches?

**Comment by KicksDNA** [comment]
I believe they are talking about disabling the monitor from posting/tweeting initial results to Slack/Twitter.

**Comment by dzt** [comment]
@KicksDNA it only sends out initial results (keyword matches) in the Slack, you can simply disable this by making `notifyWhenOnKeywordMatch` set to `false` in your `config.json` file @cjlatch125
