### ISSUE TITLE
Kith.com crashed

### ISSUE THREAD

**Issue by echodotdot** [dzt/shopify-monitor#60]
https://kith.com/sitemap_products_1.xml crashed
https://kith.com/sitemap_products_1.xml crashed
https://kithnyc.com/sitemap_products_1.xml crashed

Why kith.com crashed? is there a new .xml for kith?
i tried both kithnyc.com and kith.com and get the same error.
pls help thanks

**Comment by echodotdot** [comment]
solved

**Comment by airm45** [comment]
How did you solve it?

**Comment by db0y** [comment]
Im also getting this. How was this solved?
