### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by brandonleehsia** [dzt/shopify-monitor#61]
Is there a way to have it not list items with 0 or negative stock count?

**Comment by yourfavorite** [comment]
I haven't tested this as I don't have this code on my machine but just took a look through the source. In theory it should work.
In monitor.js you'll want to look inside the slackNotification function on line 389. Replace that line with this:
`
if (res.stock === 'Unavailable' || res.stock > 0) { 
  send(res);
}
`

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase, however I have discussed this with the creator of the project and we have decided it wouldn't be very useful, as many releases load the product beforehand with no stock, still yielding you an early link. However, if you truly want to disable this, for V2 you might want to check this line [here](https://github.com/dzt/shopify-monitor/blob/master/index.js#L148)
