### ISSUE TITLE
spam out on startup

### ISSUE THREAD

**Issue by johnclayton205** [dzt/shopify-monitor#62]
Does anyone else have this issue? I am using the keyword function as true. When i turn it on itll spam out all the items that match the specific keywords. I wish it wouldn't do this. Anyone else have the same issue? I want it to only post new items that match the keyword

**Comment by cameronb23** [comment]
Version 2 has been released with many bug fixes and an overall revamp of codebase - please attempt on version 2 and reopen if your issue/suggestion still arises, or create a new one if a different bug appears.
