### ISSUE TITLE
KEYWORDS

### ISSUE THREAD

**Issue by echodotdot** [dzt/shopify-monitor#65]
Keywords seems like not an option anymore? if i set the monitor to keyword all i get is invalid xml sites and it gives me temp banned. please help. Thanks

**Comment by dzt** [comment]
If you're not aware your getting that response due to Shopify's timing out system that's primarily been the reason why I don't touch this project that much at all because the solution to get around this would require use of rotating proxies which would be extremely expensive.

**Comment by cameronb23** [comment]
This will always be an issue as @dzt explained, but if you are running into this, consider adding proxies or slowing down the interval.
