### ISSUE TITLE
kith

### ISSUE THREAD

**Issue by Stiunit** [dzt/shopify-monitor#66]
does anyone else have any issue with kith , basically kith will spit out like 50 new items and monitor will try to tweet and send to slack . I have it searching keywords ,restocks and new items. should i just pick one ?

**Comment by esl753** [comment]
i get an Parsing Error @ https://kith.com, polling again in 300000ms

**Comment by dzt** [comment]
Kith is not worth parsing, they have a pretty strict rate limiting system that will void you from checking stock information for about 10 minutes so you'd have to have a much high interval/poll time.
