### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by ShaneAbara** [dzt/shopify-monitor#68]
Can someone help me with this error?
> $ npm start
> 
> > shopify-monitor@1.0.0 start E:\sneakers\shopify-monitor
> > node --expose_gc monitor.js
> 
> [20:07:05] Local server started on port 1337
> [20:07:05] Looking for items matching your keywords...
> [20:07:05] Currently monitoring http://shop.undefeated.com/sitemap_products_1.xm                                                                                                                                                 l
> [20:07:05] Slack Bot currently enabled.
> [20:07:05] Twitter service is currently enabled.
> [20:07:05] Getting initial data...
> [20:07:05] Interval set for every 60000ms
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE :::1337
>     at Object.exports._errnoException (util.js:1020:11)
>     at exports._exceptionWithHostPort (util.js:1043:20)
>     at Server._listen2 (net.js:1258:14)
>     at listen (net.js:1294:10)
>     at Server.listen (net.js:1390:5)
>     at EventEmitter.listen (E:\sneakers\shopify-monitor\node_modules\express\lib                                                                                                                                                 \application.js:618:24)
>     at Object.<anonymous> (E:\sneakers\shopify-monitor\monitor.js:68:5)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cl                                                                                                                                                 i.js" "start"
> npm ERR! node v6.11.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! shopify-monitor@1.0.0 start: `node --expose_gc monitor.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the shopify-monitor@1.0.0 start script 'node --expose_gc moni                                                                                                                                                 tor.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the shopify-monitor packa                                                                                                                                                 ge,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node --expose_gc monitor.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs shopify-monitor
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls shopify-monitor
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     E:\sneakers\shopify-monitor\npm-debug.log

Here's my config.json
```

{
    "interval": 60000,
    "serverPort": 1337,
    "autoRetryOnCrash": true,
    "noImageURL": "http://i.imgur.com/MdsG0Po.png",
    "notify": {
        "new": false,
        "restocks": false,
        "keywords": true
    },
    "slackBot": {
        "active": true,
        "token": "",
        "channel": "",
        "settings": {
            "username": "",
            "icon_url": "http://i.imgur.com/zks3PoZ.png"
        }
    },
    "twitter": {
        "active": true,
        "encodeImages": true,
        "consumer_key": "",
        "consumer_secret": "",
        "access_token": "",
        "access_token_secret": ""
    },
    "sites": [
        "http://shop.undefeated.com/sitemap_products_1.xml"
    ],
    "keywords": [
        "foamposite"
    ],
    "database": {
      "client": "sqlite3",
      "connection": {
        "filename": "./database/db"
      },
      "useNullAsDefault": true
    }
}
```

**Comment by cameronb23** [comment]
This error:`Error: listen EADDRINUSE :::1337` is referring to the port 1337 being currently in use by your machine. This means that your machine is using that port for another process. I suggest figuring out what process is using that port, and terminating the process.
