### ISSUE TITLE
Bot Not Showing Up As Active In The Slack, And How Do You Add The Bot To A Server To Run For ever?

### ISSUE THREAD

**Issue by Kickbasic** [dzt/shopify-monitor#69]
Bot Not Showing Up As Active In The Slack, And How Do You Add The Bot To A Server To Run For ever?

**Comment by cameronb23** [comment]
Unsure of what you exactly the issue you are requesting help for, but in the future I believe the monitor will be using Slack/Discord webhooks which means it will not be a "bot user" per-se, but will just post a message on product update. However, if you want to run this indefinitely, you can use a multitude of methods. Most useful in my opinion would be [PM2](http://pm2.keymetrics.io/), but you could also use a simple solution on a server such as [Screen on Linux](https://www.gnu.org/software/screen/manual/screen.html#Getting-Started). Hope this helps.

**Comment by cameronb23** [comment]
Closing as I believe I sufficiently answered your questions. If you have any further questions feel free to reopen.
