### ISSUE TITLE
twitter config is not tweeting out

### ISSUE THREAD

**Issue by thesolechef** [dzt/shopify-monitor#7]
hey, i set up my twitter and gave all the requested info. it is not tweeting out although monitor shows new items added

**Comment by dzt** [comment]
The info is being pushed over. Ensure that your keys are correct if you have issues please regenerate them. I had this issue requiring me to regenerate my tokens/keys.

**Comment by thesolechef** [comment]
Okay. I assume it only tweets when a match is found and not when a new item is added? Also, as for  the "match found"'s that appear once monitor is started, are those supposed to be tweeted out? or is it every match found after those.

**Comment by dzt** [comment]
@thesolechef Yeah, it only tweets out new matches and restocks as mentioned in the [docs](https://github.com/dzt/shopify-monitor/wiki/Twitter)

**Comment by thesolechef** [comment]
Okay. Too clarify, when I start the monitor, all the "Match Found"'s that appear are supposed to be being tweeted?

**Comment by mrmark0123** [comment]
https://i.gyazo.com/c0ecca90eaa21e7d1978db6390fe1222.mp4

**Comment by thesolechef** [comment]
I am not seeing anything like that. no indication of any tweeting. i regenerated the codes as well.

**Comment by dzt** [comment]
@thesolechef as stated in the documentation/wiki under the Twitter section, it only tweets new tweets and restocks.

**Comment by dzt** [comment]
@mrmark0123 Your interval is way too low.

**Comment by thesolechef** [comment]
I know my man. I have running for over 20 shopify sites with the correct links where a few restocks have already taken place.

**Comment by dzt** [comment]
@thesolechef So, is it working fine for you now?

**Comment by thesolechef** [comment]
still no tweets being made. does it have anything to do with the twitter being a private account?

**Comment by cjlatch125** [comment]
@thesolechef how do u have 20 sites running at that rate w/o it crashing due to memory errors, i have like 15 running with a slower refresh and its running out of memory like every 10 minutes.

**Comment by thesolechef** [comment]
any word on my issue @dzt ? and you have to change the node memory cap to somewhere around 4096. standard is like around 500 i think

**Comment by thesolechef** [comment]
@cjlatch125

**Comment by KicksDNA** [comment]
I have the same issue as well. I get the "Twitter service is currently enabled." message but after that the program doesn't reference Twitter at all. Not even an error message saying a tweet wasn't able too be sent. I regenerated my keys as well.

**Comment by ronmo32992** [comment]
following. [00:28:09] No new updates found yet but still looking 

not sure if it will come up on twitter, will test it
