### ISSUE TITLE
Knex Timeout Error

### ISSUE THREAD

**Issue by cameronb23** [dzt/shopify-monitor#72]
`[Wed Nov 01 2017 17:11:23] [LOG]   err { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

I'm assuming this is a lack of resources to connect to the SQLite database. Produced on latest PR.

**Comment by kzmustang** [comment]
got the same error

**Comment by tuturkiener** [comment]
same for me

**Comment by Kickbasic** [comment]
Same here please lmk if anyone has a fix for it🙏🏻

**Comment by dzt** [comment]
Seems like a Windows specific error, I'll look into it as soon as I get home, Thanks.

**Comment by Kickbasic** [comment]
Did you find the fix yet? @dzt

**Comment by cameronb23** [comment]
@Kickbasic please do not keep spamming the Github issues. You can be notified of updates if you click subscribe on the right side of this issue.

**Comment by Kickbasic** [comment]
thanks didnt know that and sorry about the spam

**Comment by cameronb23** [comment]
Reproduced on both the following environments:

Ubuntu 14.04 trusty
node version 8.9.0
npm version 5.5.1

also reproduced on macOS by another user.
node version 8.9.0
npm version 5.5.1

**Comment by cameronb23** [comment]
If anyone was wondering, the answer is to increase the `acquireConnectionTimeout` variable in the config as published here: 05a90d2
