### ISSUE TITLE
Add To Cart

### ISSUE THREAD

**Issue by esl753** [dzt/shopify-monitor#73]
Looks like the add to cart links on shopify have changed?

**Comment by GainorB** [comment]
Yes they did, looks like an extra .js file is used during the carting process

**Comment by cameronb23** [comment]
Examples of this? I haven't noticed a change yet but I haven't checked.

**Comment by cameronb23** [comment]
According to the current codebase all ATC URLs (as far as I can see) are up to date with the current pattern of `/cart/variant:qty`. This is shown accurately [here](https://github.com/dzt/shopify-monitor/blob/master/utils/api.js#L60).

**Comment by Jeisonx3** [comment]
i don't know if they mean this but, in slack when you click on one of the ATC link it will open a tab with the following.
foundItemURL/cart/variant:qty
<img width="547" alt="screen shot 2017-11-03 at 1 32 40 pm" src="https://user-images.githubusercontent.com/22186712/32387684-a1a249f0-c09b-11e7-94ae-514b139ffb03.png">

when it should be.
siteURL/cart/variant:qty
<img width="337" alt="screen shot 2017-11-03 at 1 32 59 pm" src="https://user-images.githubusercontent.com/22186712/32387687-a6a6348e-c09b-11e7-8997-f992d74782c7.png">

**Comment by cameronb23** [comment]
Ah. I see. I'll check it out, thanks! 👍

**Comment by cameronb23** [comment]
Should be fixed in 3b4a0d5. Thanks 💯
