### ISSUE TITLE
Respond with object instead of direct URL

### ISSUE THREAD

**Issue by cameronb23** [dzt/shopify-monitor#75]
In API we respond to getStockData with direct URLs as shown [here](https://github.com/dzt/shopify-monitor/blob/master/utils/api.js#L61). I suggest responding with an object containing variant ID and size title so that we can correctly format for different platforms in future.

**Comment by cameronb23** [comment]
#77 pr created.

**Comment by Kickbasic** [comment]
How do we fix the knex error

**Comment by cameronb23** [comment]
Hi @Kickbasic, please refer to the [issue](https://github.com/dzt/shopify-monitor/issues/72) that has been created for that bug. This is for a different topic and should not be used for that discussion.
