### ISSUE TITLE
npm 

### ISSUE THREAD

**Issue by joshszn** [dzt/shopify-monitor#76]
updated node already, still wont allow an install.

$ npm install

> sqlite3@3.1.13 install C:\Users\Josh\shopify-monitor\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Josh\AppData\Roaming\npm-cache\_logs\2017-11-03T18_12_50_928Z-debug.log

**Comment by cameronb23** [comment]
Please read the instructions. Both Node & NPM are required to run this.
