### ISSUE TITLE
pollTimeMS

### ISSUE THREAD

**Issue by debugestrada** [dzt/shopify-monitor#78]
Keep getting "This page is temporarily unavailable because a device from your location is sending large amounts of web requests. Visitors from other locations can still view the page." 

Any way I can get around this?

**Comment by Jeisonx3** [comment]
increase your pollTimeMs in config.json or use proxies.

**Comment by cameronb23** [comment]
@debugestrada It's shopify ratelimiting. You need to add proxies or greatly increase your polling time.
