### ISSUE TITLE
Keywords with 2.0 Version

### ISSUE THREAD

**Issue by Chrisz0rSMG** [dzt/shopify-monitor#79]
Is there a way to use keywords in the 2.0 version? I noticed the new config.json is completely different from the 1.0 version.

**Comment by fredbrzoska** [comment]
I would also like to know

**Comment by cameronb23** [comment]
At the moment we are currently dealing with some other issues, but you can see [here](https://github.com/dzt/shopify-monitor/blob/master/service.js#L45) that it is on our list. We will provide updates soon :)

**Comment by cameronb23** [comment]
If anyone is wondering, I will be attempting to implement this in the coming few days. Hopefully in time for the beloved YEEZY szn... 💯

**Comment by cameronb23** [comment]
For any still watching this thread, see commits 49af496 and aecc5f8 for updates. Thanks 💯
