### ISSUE TITLE
Parsing error | connection error

### ISSUE THREAD

**Issue by Zero-01010** [dzt/shopify-monitor#82]
When setting up monitor with or without proxies i get only parsing errors and connection errors

**Comment by jrodwhit** [comment]
Same.  Even when running only 3 sites (with plenty of proxies), I get parsing error with anything less than a 10000ms delay

**Comment by cameronb23** [comment]
Not related to any code-related issues, unless you can provide an error other than being ratelimited.

**Comment by XioYang23** [comment]
Lol its a parsing erros because shopify bann

This script does not use your proxies it only count thems 

If you check after parsing error and go on a shopify site banned because this script

is not in fact using any proxies to handle any requests it is only counting the proxies

**Comment by Zero-01010** [comment]
@XioYang23 LMAO So many Ls and this made my morning! Thanks

**Comment by dzt** [comment]
@xioyang23 Before you make assumptions you might as well check the source yourself, if you want log it as well. No it does not count proxies, it uses them. Grow up. https://github.com/dzt/shopify-monitor/blob/master/service.js

**Comment by cameronb23** [comment]
commit c77497f
