### ISSUE TITLE
Not a problem | is XML site monitoring working

### ISSUE THREAD

**Issue by Zero-01010** [dzt/shopify-monitor#86]

**Comment by Zero-01010** [comment]
Wondering if sitemap monitoring is still an option?

**Comment by cameronb23** [comment]
Yes. This is how it is currently monitored.

**Comment by cris2011** [comment]
How come some websites are getting errors?

![pasted image at 2017_11_20 09_45 pm](https://user-images.githubusercontent.com/19259093/33088937-c10ca822-ceb4-11e7-89ba-8e98804cf73d.png)

**Comment by cameronb23** [comment]
@cris2011 This is how Shopify works. All sites that are hosted on Shopify(99%), are under the same ratelimiting system. Connection errors are something wrong that is disallowing the monitor from CONNECTING to the website and receiving a response, and parsing errors are most likely being ratelimited by shopify. However, I have included an update that writes error logs, as you can see, so you can check what is going on. Let me know if you have any further issues.

**Comment by ajshaffer** [comment]
I am getting connection errors to every website I have in the config.json. I go on regular browser and I am still able to access the site?
