### ISSUE TITLE
'pm2' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by joshszn** [dzt/shopify-monitor#89]
'pm2' is not recognized as an internal or external command,
operable program or batch file.
 
placed pm2 bin in path and still error :/

**Comment by joshszn** [comment]
found the issue

**Comment by leonardoResendeLima** [comment]
@joshszn Can you please share the solution.

**Comment by dzt** [comment]
@leonardoResendeLima Follow the instructions [here](https://github.com/dzt/shopify-monitor/blob/master/README.md)

**Comment by sujeshuv** [comment]
> found the issue

how did you solve this ?

**Comment by kajoseph** [comment]
For future users, my issue was that my NODE_PATH environment variable disappeared somehow. I readded the env variable pointed to the node_modules folder in my Node installation folder and it works now.
