### ISSUE TITLE
Error when starting to run

### ISSUE THREAD

**Issue by hayess89** [dzt/shopify-monitor#97]
0|shopify- |     at compile (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:103:45)
0|shopify- |     at loader (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:144:14)
0|shopify- |     at Object.require.extensions.(anonymous function) [as .js] (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:154:7)
0|shopify- |     at Module.load (module.js:554:32)
0|shopify- | Error: Couldn't find preset "es2017" relative to directory "C:\\Sneaker Bots\\Monitors\\shopify-monitor-master"
0|shopify- |     at C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
0|shopify- |     at Array.map (<anonymous>)
0|shopify- |     at OptionManager.resolvePresets (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
0|shopify- |     at OptionManager.mergePresets (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
0|shopify- |     at OptionManager.mergeOptions (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
0|shopify- |     at OptionManager.init (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
0|shopify- |     at compile (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:103:45)
0|shopify- |     at loader (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:144:14)
0|shopify- |     at Object.require.extensions.(anonymous function) [as .js] (C:\Sneaker Bots\Monitors\shopify-monitor-master\node_modules\babel-register\lib\node.js:154:7)
0|shopify- |     at Module.load (module.js:554:32)

**Comment by hayess89** [comment]
probably something i haven't done right. Any help would be great thx in advance

**Comment by maximvanneste** [comment]
did you do npm install and pm2 install -g ?

**Comment by hayess89** [comment]
Yes I had done.

I have deleted and started again. Hopefully I will work this time round.

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bennt1** [comment]
babel.rc has setting
 {
  "presets": ["es2017"] or ["es2015"]  make sure you have that preset matching the babel version you have installed. 
  
}

**Comment by hayess89** [comment]
Solved thanks for the help
